name: mkdir example

on:
  push:
    branches: [ '**' ]
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
      
      # - name: Create dir
      #   run: |
      #     cd src
      #     cat *.js > cookiebrain.js
      #     cd ..
      #     mv src/cookiebrain.js dist/cookiebrain.js
      #     cp src/cookiebrain.css dist/cookiebrain.css
      #     cp -r images dist/images
      #     cp -r sounds dist/sounds
          
      #     - uses: stefanzweifel/git-auto-commit-action@v4

      - name: SFTP Upload
        # You may pin to the exact commit or the version.
        # uses: Dylan700/sftp-upload-action@f90db607d9fe1acdc0eefccee84d37c119b268fe
        uses: Dylan700/sftp-upload-action@v1.1.4
        with:
          # The SFTP server (e.g. sftp.server.com).
          server: ${{ secrets.address }}
          # The SFTP username.
          username: ${{ secrets.user }}
          # The private key.
          key: ${{ secrets.key }}
          uploads: |
            ./ => ${{ secrets.path }}
          ignore: |
            *.git
            .github
            .github/
            .gitignore
            .gitattribbutes
            README.md  
