name: cookieclicker-push-action
run-name: ${{ github.actor }} is doing it's thing
on: [push]
jobs:
  combine-js:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir $HOME/dist
      - run: find $HOME/src/ -name *.js -exec cat {} + > $HOME/dist/cookiebrain.js
