name: mkdir example

on:
  push:
    branches: [ '**' ]
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Create dir
        run: |
          cd src
          cat *.js > cookiebrain.js
          cd ..
          mv src/cookiebrain.js dist/cookiebrain.js
          cp src/cookiebrain.css dist/cookiebrain.css
          
      - uses: stefanzweifel/git-auto-commit-action@v4

      - name: SFTP Deploy
        # You may pin to the exact commit or the version.
        # uses: wlixcc/SFTP-Deploy-Action@da88a4dbe95286266bbac3c0b2b8284048d20c8f
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          # username
          username: ${{ env.SERVER1_USER }}
          # your sftp server
          server: ${{ env.SERVER1_ADDR }}
          # your sftp server port, default to 22
          port: 22
          # you can copy private_key from your *.pem file, keep format
          ssh_private_key: ${{ secrets.SERVER1_PPK }}
          # will put all file under this path
          local_path: ./dist/
          # files will copy to under remote_path
          remote_path: ${{ env.SERVER1_PATH }}
          # connection via sftp protocol only
          sftp_only: # optional
          # sftp args
          sftpArgs: # optional
          # This operation will delete all files in the remote path before upload. Please be careful set this to true
          delete_remote_files: # optional
          # SSH passsword，If a password is set, the secret key pair is ignored
          password: ${{ secrets.SERVER1_PASS }}