name: mkdir example

on:
  push:
    branches: [ '**' ]
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create dir
        run: |
          mkdir mydirname
          touch mydirname/test.txt
          echo "This is a sample text" > mydirname/test.txt
      - name: GIT commit and push
        env: 
          CI_COMMIT_MESSAGE: Auto commit and push
          CI_COMMIT_AUTHOR: AutoCommit
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add docs
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
