name: mkdir example

on:
  push:
    branches: [ '**' ]
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Create dir
        run: |
          cd src
          cat *.js > cookiebrain.js
          cd ..
          mv src/cookiebrain.js dist/cookiebrain.js
          cp src/cookiebrain.css dist/cookiebrain.css
          
      - uses: stefanzweifel/git-auto-commit-action@v4

      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ env.address }}
          password: ${{ secrets.pass }}
          port: 22
          localDir: './dist/'
          remoteDir: ${{ env.path }}
          privateKey: ${{ secrets.key }}
          passphrase: ${{ secrets.pass }}
          exclude: '.git*,.DS_Store'