name: mkdir example

on:
  push:
    branches: [ '**' ]
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create dir
        run: |
          mkdir mydirname
          touch mydirname/test.txt
          echo "This is a sample text" > mydirname/test.txt
          git commit -m "Automated test"
          git push
