name: cookieclicker-push-action
run-name: ${{ github.actor }} is doing it's thing
on: [push]
jobs:
  combine-js:
    runs-on: ubuntu-latest
    steps:
      - name: Create dir
        run: |
          mkdir dist
          find src/ -name *.js -exec cat {} + > dist/cookiebrain.js
