name: mkdir example

on:
  push:
    branches: [ '**' ]
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Create dir
        run: |
          mkdir mydirname
          touch mydirname/test.txt
          echo "This is a sample text" > mydirname/test.txt
          
      - uses: stefanzweifel/git-auto-commit-action@v4
