name: mkdir example

on:
  push:
    branches: [ '**' ]
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Create dir
        run: |
          cd src
          cat *.js > cookiebrain.js
          cd ..
          mv src/cookiebrain.js dist/cookiebrain.js
          cp src/cookiebrain.css dist/cookiebrain.css
          
      - uses: stefanzweifel/git-auto-commit-action@v4

      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: env.SERVER1_ADDR
          port: 22
          username: # optional, default is root
          password: 
          compress: # optional
          localDir: ./dist/
          remoteDir: env.SERVER1_PATH
          dryRun: # optional
          privateKey: secrets.SERVER1_PPK
          passphrase: secrets.SERVER1_PASS
          agent: # optional, default is 
          exclude: # optional, default is 
          forceUpload: # optional
          removeExtraFilesOnServer: # optional