name: cookieclicker-push-action
run-name: ${{ github.actor }} is doing it's thing
on: [push]
jobs:
  combine-js:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir dist
      - run: cat ./src/*.js > ./dist/cookiebrain.js
