name: mkdir example

on:
  push:
    branches: [ '**' ]
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Create dir
        run: |
          cd src
          cat *.js > cookiebrain.js
          cd ..
          mv src/cookiebrain.js dist/cookiebrain.js
          
      - uses: stefanzweifel/git-auto-commit-action@v4